
class\
W0rStHeLloWoRlD\
    :
    def\
    __init__\
    (\
    self\
    ):
        self\
            .\
        ArrAy\
            =\
                []
        
        self\
            .\
            ArrAy_Add\
            (\
            )

    def\
        ArrAy_Add\
            (\
                self\
                )\
                :
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    H\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    E\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    L\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    L\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    O\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    -\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    W\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    O\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    R\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    L\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )
                self\
                    .\
                    ArrAy\
                        .\
                        append\
                            (\
                                '\
                                    D\
                                        '.\
                                            strip\
                                                (\
                                                    ' '\
                                                        )\
                                                            )

                h\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        0\
                                            ]\
                                                )
                e\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        1\
                                            ]\
                                                )
                l\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        2\
                                            ]\
                                                )
                ll\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        3\
                                            ]\
                                                )
                o\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        4\
                                            ]\
                                                )
                x\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        5\
                                            ]\
                                                )
                w\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        6\
                                            ]\
                                                )
                o\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        7\
                                            ]\
                                                )
                r\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        8\
                                            ]\
                                                )
                lx\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        9\
                                            ]\
                                                )
                d\
                    =\
                    (\
                        self\
                            .\
                                ArrAy\
                                    [\
                                        10\
                                            ]\
                                                )
                strinG = \
                    (\
                    "{}{}{}{}{}{}{}{}{}{}{}"\
                        .\
                            format\
                                (\
                                    h\
                                        ,\
                                            e\
                                                ,\
                                                    l\
                                                        ,\
                                                            ll,\
                                                                o,\
                                                                    x,\
                                                                        w,\
                                                                            o,\
                                                                                r,\
                                                                                    lx,\
                                                                                        d\
                                                                                            )\
                                                                                                )
                
                print\
                    (\
                        strinG\
                            .\
                                strip\
                                    (\
                                        ' '\
                                            )\
                                                )
              


if\
    __name__\
        ==\
            '__main__'\
                :
                ClAssVaRiable\
                    =\
                    W0rStHeLloWoRlD\
                    ()
   
